[oauth]
client_id="050c8086-3015-4bdc-a93e-889da3fdbd45"
client_secret="Yos8Q~ENcTmCcJvPd9Jfo4THHVurMqcRqDI4HaHr"
tenant_id="a3bf2aac-b2b7-4212-bed7-ff2ead69af12"
REDIRECT_URI="https://5015d77f4d00.ngrok-free.app"